// export const Adress = "http://127.0.0.1:8000/";
export const Adress = import.meta.env.VITE_BACKEND_API

export const countryList = [
  { name: "Afghanistan***Afganistán", code: "AF" },
  { name: "Åland Islands***Islas Åland", code: "AX" },
  { name: "Albania***Albania", code: "AL" },
  { name: "Algeria***Argelia", code: "DZ" },
  { name: "American Samoa***Samoa Americana", code: "AS" },
  { name: "Andorra***Andorra", code: "AD" },
  { name: "Angola***Angola", code: "AO" },
  { name: "Anguilla***Anguila", code: "AI" },
  { name: "Antarctica***Antártida", code: "AQ" },
  { name: "Antigua and Barbuda***Antigua y Barbuda", code: "AG" },
  { name: "Argentina***Argentina", code: "AR" },
  { name: "Armenia***Armenia", code: "AM" },
  { name: "Aruba***Aruba", code: "AW" },
  { name: "Australia***Australia", code: "AU" },
  { name: "Austria***Austria", code: "AT" },
  { name: "Azerbaijan***Azerbaiyán", code: "AZ" },
  { name: "Bahamas***Bahamas", code: "BS" },
  { name: "Bahrain***Baréin", code: "BH" },
  { name: "Bangladesh***Bangladés", code: "BD" },
  { name: "Barbados***Barbados", code: "BB" },
  { name: "Belarus***Bielorrusia", code: "BY" },
  { name: "Belgium***Bélgica", code: "BE" },
  { name: "Belize***Belice", code: "BZ" },
  { name: "Benin***Benín", code: "BJ" },
  { name: "Bermuda***Bermudas", code: "BM" },
  { name: "Bhutan***Bután", code: "BT" },
  { name: "Bolivia***Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina***Bosnia y Herzegovina", code: "BA" },
  { name: "Botswana***Botsuana", code: "BW" },
  { name: "Bouvet Island***Isla Bouvet", code: "BV" },
  { name: "Brazil***Brasil", code: "BR" },
  {
    name: "British Indian Ocean Territory***Territorio Británico del Océano Índico",
    code: "IO",
  },
  { name: "Brunei Darussalam***Bruneí", code: "BN" },
  { name: "Bulgaria***Bulgaria", code: "BG" },
  { name: "Burkina Faso***Burkina Faso", code: "BF" },
  { name: "Burundi***Burundi", code: "BI" },
  { name: "Cambodia***Camboya", code: "KH" },
  { name: "Cameroon***Camerún", code: "CM" },
  { name: "Canada***Canadá", code: "CA" },
  { name: "Cape Verde***Cabo Verde", code: "CV" },
  { name: "Cayman Islands***Islas Caimán", code: "KY" },
  { name: "Central African Republic***República Centroafricana", code: "CF" },
  { name: "Chad***Chad", code: "TD" },
  { name: "Chile***Chile", code: "CL" },
  { name: "China***China", code: "CN" },
  { name: "Christmas Island***Isla de Navidad", code: "CX" },
  { name: "Cocos (Keeling) Islands***Islas Cocos (Keeling)", code: "CC" },
  { name: "Colombia***Colombia", code: "CO" },
  { name: "Comoros***Comoras", code: "KM" },
  { name: "Congo***Congo", code: "CG" },
  {
    name: "Congo, The Democratic Republic of the***República Democrática del Congo",
    code: "CD",
  },
  { name: "Cook Islands***Islas Cook", code: "CK" },
  { name: "Costa Rica***Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire***Costa de Marfil", code: "CI" },
  { name: "Croatia***Croacia", code: "HR" },
  { name: "Cuba***Cuba", code: "CU" },
  { name: "Cyprus***Chipre", code: "CY" },
  { name: "Czech Republic***Chequia", code: "CZ" },
  { name: "Denmark***Dinamarca", code: "DK" },
  { name: "Djibouti***Yibuti", code: "DJ" },
  { name: "Dominica***Dominica", code: "DM" },
  { name: "Dominican Republic***República Dominicana", code: "DO" },
  { name: "Ecuador***Ecuador", code: "EC" },
  { name: "Egypt***Egipto", code: "EG" },
  { name: "El Salvador***El Salvador", code: "SV" },
  { name: "Equatorial Guinea***Guinea Ecuatorial", code: "GQ" },
  { name: "Eritrea***Eritrea", code: "ER" },
  { name: "Estonia***Estonia", code: "EE" },
  { name: "Ethiopia***Etiopía", code: "ET" },
  { name: "Falkland Islands (Malvinas)***Islas Malvinas", code: "FK" },
  { name: "Faroe Islands***Islas Feroe", code: "FO" },
  { name: "Fiji***Fiyi", code: "FJ" },
  { name: "Finland***Finlandia", code: "FI" },
  { name: "France***Francia", code: "FR" },
  { name: "French Guiana***Guayana Francesa", code: "GF" },
  { name: "French Polynesia***Polinesia Francesa", code: "PF" },
  {
    name: "French Southern Territories***Territorios Australes Franceses",
    code: "TF",
  },
  { name: "Gabon***Gabón", code: "GA" },
  { name: "Gambia***Gambia", code: "GM" },
  { name: "Georgia***Georgia", code: "GE" },
  { name: "Germany***Alemania", code: "DE" },
  { name: "Ghana***Ghana", code: "GH" },
  { name: "Gibraltar***Gibraltar", code: "GI" },
  { name: "Greece***Grecia", code: "GR" },
  { name: "Greenland***Groenlandia", code: "GL" },
  { name: "Grenada***Granada", code: "GD" },
  { name: "Guadeloupe***Guadalupe", code: "GP" },
  { name: "Guam***Guam", code: "GU" },
  { name: "Guatemala***Guatemala", code: "GT" },
  { name: "Guernsey***Guernesey", code: "GG" },
  { name: "Guinea***Guinea", code: "GN" },
  { name: "Guinea-Bissau***Guinea-Bisáu", code: "GW" },
  { name: "Guyana***Guyana", code: "GY" },
  { name: "Haiti***Haití", code: "HT" },
  {
    name: "Heard Island and Mcdonald Islands***Islas Heard y McDonald",
    code: "HM",
  },
  {
    name: "Holy See (Vatican City State)***Santa Sede (Estado de la Ciudad del Vaticano)",
    code: "VA",
  },
  { name: "Honduras***Honduras", code: "HN" },
  { name: "Hong Kong***Hong Kong", code: "HK" },
  { name: "Hungary***Hungría", code: "HU" },
  { name: "Iceland***Islandia", code: "IS" },
  { name: "India***India", code: "IN" },
  { name: "Indonesia***Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of***Irán", code: "IR" },
  { name: "Iraq***Irak", code: "IQ" },
  { name: "Ireland***Irlanda", code: "IE" },
  { name: "Isle of Man***Isla de Man", code: "IM" },
  { name: "Israel***Israel", code: "IL" },
  { name: "Italy***Italia", code: "IT" },
  { name: "Jamaica***Jamaica", code: "JM" },
  { name: "Japan***Japón", code: "JP" },
  { name: "Jersey***Jersey", code: "JE" },
  { name: "Jordan***Jordania", code: "JO" },
  { name: "Kazakhstan***Kazajistán", code: "KZ" },
  { name: "Kenya***Kenia", code: "KE" },
  { name: "Kiribati***Kiribati", code: "KI" },
  {
    name: "Korea, Democratic People's Republic of***Corea del Norte",
    code: "KP",
  },
  { name: "Korea, Republic of***Corea del Sur", code: "KR" },
  { name: "Kuwait***Kuwait", code: "KW" },
  { name: "Kyrgyzstan***Kirguistán", code: "KG" },
  { name: "Lao People's Democratic Republic***Laos", code: "LA" },
  { name: "Latvia***Letonia", code: "LV" },
  { name: "Lebanon***Líbano", code: "LB" },
  { name: "Lesotho***Lesoto", code: "LS" },
  { name: "Liberia***Liberia", code: "LR" },
  { name: "Libya***Libia", code: "LY" },
  { name: "Liechtenstein***Liechtenstein", code: "LI" },
  { name: "Lithuania***Lituania", code: "LT" },
  { name: "Luxembourg***Luxemburgo", code: "LU" },
  { name: "Macao***Macao", code: "MO" },
  { name: "Madagascar***Madagascar", code: "MG" },
  { name: "Malawi***Malaui", code: "MW" },
  { name: "Malaysia***Malasia", code: "MY" },
  { name: "Maldives***Maldivas", code: "MV" },
  { name: "Mali***Malí", code: "ML" },
  { name: "Malta***Malta", code: "MT" },
  { name: "Marshall Islands***Islas Marshall", code: "MH" },
  { name: "Martinique***Martinica", code: "MQ" },
  { name: "Mauritania***Mauritania", code: "MR" },
  { name: "Mauritius***Mauricio", code: "MU" },
  { name: "Mayotte***Mayotte", code: "YT" },
  { name: "Mexico***México", code: "MX" },
  { name: "Micronesia, Federated States of***Micronesia", code: "FM" },
  { name: "Moldova, Republic of***Moldavia", code: "MD" },
  { name: "Monaco***Mónaco", code: "MC" },
  { name: "Mongolia***Mongolia", code: "MN" },
  { name: "Montenegro***Montenegro", code: "ME" },
  { name: "Montserrat***Montserrat", code: "MS" },
  { name: "Morocco***Marruecos", code: "MA" },
  { name: "Mozambique***Mozambique", code: "MZ" },
  { name: "Myanmar***Birmania", code: "MM" },
  { name: "Namibia***Namibia", code: "NA" },
  { name: "Nauru***Nauru", code: "NR" },
  { name: "Nepal***Nepal", code: "NP" },
  { name: "Netherlands***Países Bajos", code: "NL" },
  { name: "New Caledonia***Nueva Caledonia", code: "NC" },
  { name: "New Zealand***Nueva Zelanda", code: "NZ" },
  { name: "Nicaragua***Nicaragua", code: "NI" },
  { name: "Niger***Níger", code: "NE" },
  { name: "Nigeria***Nigeria", code: "NG" },
  { name: "Niue***Niue", code: "NU" },
  { name: "Norfolk Island***Isla Norfolk", code: "NF" },
  { name: "North Macedonia***Macedonia del Norte", code: "MK" },
  { name: "Northern Mariana Islands***Islas Marianas del Norte", code: "MP" },
  { name: "Norway***Noruega", code: "NO" },
  { name: "Oman***Omán", code: "OM" },
  { name: "Pakistan***Pakistán", code: "PK" },
  { name: "Palau***Palaos", code: "PW" },
  { name: "Palestine, State of***Palestina", code: "PS" },
  { name: "Panama***Panamá", code: "PA" },
  { name: "Papua New Guinea***Papúa Nueva Guinea", code: "PG" },
  { name: "Paraguay***Paraguay", code: "PY" },
  { name: "Peru***Perú", code: "PE" },
  { name: "Philippines***Filipinas", code: "PH" },
  { name: "Pitcairn***Pitcairn", code: "PN" },
  { name: "Poland***Polonia", code: "PL" },
  { name: "Portugal***Portugal", code: "PT" },
  { name: "Puerto Rico***Puerto Rico", code: "PR" },
  { name: "Qatar***Catar", code: "QA" },
  { name: "Réunion***Reunión", code: "RE" },
  { name: "Romania***Rumania", code: "RO" },
  { name: "Russian Federation***Rusia", code: "RU" },
  { name: "Rwanda***Ruanda", code: "RW" },
  { name: "Saint Barthélemy***San Bartolomé", code: "BL" },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha***Santa Elena, Ascensión y Tristán de Acuña",
    code: "SH",
  },
  { name: "Saint Kitts and Nevis***San Cristóbal y Nieves", code: "KN" },
  { name: "Saint Lucia***Santa Lucía", code: "LC" },
  {
    name: "Saint Martin (French part)***San Martín (parte francesa)",
    code: "MF",
  },
  { name: "Saint Pierre and Miquelon***San Pedro y Miquelón", code: "PM" },
  {
    name: "Saint Vincent and the Grenadines***San Vicente y las Granadinas",
    code: "VC",
  },
  { name: "Samoa***Samoa", code: "WS" },
  { name: "San Marino***San Marino", code: "SM" },
  { name: "Sao Tome and Principe***Santo Tomé y Príncipe", code: "ST" },
  { name: "Saudi Arabia***Arabia Saudita", code: "SA" },
  { name: "Senegal***Senegal", code: "SN" },
  { name: "Serbia***Serbia", code: "RS" },
  { name: "Seychelles***Seychelles", code: "SC" },
  { name: "Sierra Leone***Sierra Leona", code: "SL" },
  { name: "Singapore***Singapur", code: "SG" },
  { name: "Slovakia***Eslovaquia", code: "SK" },
  { name: "Slovenia***Eslovenia", code: "SI" },
  { name: "Solomon Islands***Islas Salomón", code: "SB" },
  { name: "Somalia***Somalia", code: "SO" },
  { name: "South Africa***Sudáfrica", code: "ZA" },
  {
    name: "South Georgia and the South Sandwich Islands***Islas Georgias del Sur y Sandwich del Sur",
    code: "GS",
  },
  { name: "South Sudan***Sudán del Sur", code: "SS" },
  { name: "Spain***España", code: "ES" },
  { name: "Sri Lanka***Sri Lanka", code: "LK" },
  { name: "Sudan***Sudán", code: "SD" },
  { name: "Suriname***Surinam", code: "SR" },
  { name: "Svalbard and Jan Mayen***Svalbard y Jan Mayen", code: "SJ" },
  { name: "Sweden***Suecia", code: "SE" },
  { name: "Switzerland***Suiza", code: "CH" },
  { name: "Syrian Arab Republic***Siria", code: "SY" },
  { name: "Taiwan, Province of China***Taiwán", code: "TW" },
  { name: "Tajikistan***Tayikistán", code: "TJ" },
  { name: "Tanzania, United Republic of***Tanzania", code: "TZ" },
  { name: "Thailand***Tailandia", code: "TH" },
  { name: "Timor-Leste***Timor Oriental", code: "TL" },
  { name: "Togo***Togo", code: "TG" },
  { name: "Tokelau***Tokelau", code: "TK" },
  { name: "Tonga***Tonga", code: "TO" },
  { name: "Trinidad and Tobago***Trinidad y Tobago", code: "TT" },
  { name: "Tunisia***Túnez", code: "TN" },
  { name: "Turkey***Turquía", code: "TR" },
  { name: "Turkmenistan***Turkmenistán", code: "TM" },
  { name: "Turks and Caicos Islands***Islas Turcas y Caicos", code: "TC" },
  { name: "Tuvalu***Tuvalu", code: "TV" },
  { name: "Uganda***Uganda", code: "UG" },
  { name: "Ukraine***Ucrania", code: "UA" },
  { name: "United Arab Emirates***Emiratos Árabes Unidos", code: "AE" },
  { name: "United Kingdom***Reino Unido", code: "GB" },
  { name: "United States***Estados Unidos", code: "US" },
  {
    name: "United States Minor Outlying Islands***Islas Ultramarinas Menores de Estados Unidos",
    code: "UM",
  },
  { name: "Uruguay***Uruguay", code: "UY" },
  { name: "Uzbekistan***Uzbekistán", code: "UZ" },
  { name: "Vanuatu***Vanuatu", code: "VU" },
  { name: "Venezuela***Venezuela", code: "VE" },
  { name: "Vietnam***Vietnam", code: "VN" },
  { name: "Virgin Islands, British***Islas Vírgenes Británicas", code: "VG" },
  {
    name: "Virgin Islands, U.S.***Islas Vírgenes de los Estados Unidos",
    code: "VI",
  },
  { name: "Wallis and Futuna***Wallis y Futuna", code: "WF" },
  { name: "Western Sahara***Sahara Occidental", code: "EH" },
  { name: "Yemen***Yemen", code: "YE" },
  { name: "Zambia***Zambia", code: "ZM" },
  { name: "Zimbabwe***Zimbabue", code: "ZW" },
];
